= vue3-counter-server-jest-cypress

== Project setup

[source,shell]
----
npm install
----

=== Compiles and hot-reloads for development

[source,shell]
----
npm run serve
----

=== Compiles and minifies for production

. Fix public path to output GitHub Pages (Optional)
+
[source,javascript]
.vue.config.js
----
module.exports = {
  publicPath:
    process.env.NODE_ENV === "production" ? "/vue3-counter-server/" : "/",
};
----

. Build for production
+
[source,shell]
----
npm run build
----

=== Run your unit tests

[source,shell]
----
npm run test:unit
----

=== Run your end-to-end tests

[source,shell]
----
npm run test:e2e
----

=== Lints and fixes files

[source,shell]
----
npm run lint
----

=== Customize configuration
See https://cli.vuejs.org/config/[Configuration Reference^].

=== Update

==== Update browser list

[source,shell]
----
npx browserslist@latest --update-db
----

==== Fix some vulnerabilities

* Show a security audit
+
[source,shell]
----
npm audit
----

* Fix some vulnerabilities
+
[source,shell]
----
npm audit fix
----

==== Update Vue CLI from v4 to v5

See https://cli.vuejs.org/migrations/migrate-from-v4.html[Migrate from v4 | Vue CLI^].

* Check Vue CLI version
+
[source,console]
----
> npm ls -g @vue/cli
C:\Program Files (x86)\Nodist\bin
└── @vue/cli@4.5.13
----

* First, install the latest Vue CLI globally:
+
[source,console]
----
> npm install -g @vue/cli
...
> npm ls -g @vue/cli     
C:\Program Files (x86)\Nodist\bin
└── @vue/cli@5.0.8
----

* Upgrade an existing project from v4 to v5
+
[source,console]
----
> vue upgrade
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes
✔  Gathering package information...
  Name                         Installed       Wanted          Latest          Command to upgrade
  @vue/cli-service             4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-service
  @vue/cli-plugin-e2e-cypress  4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-plugin-e2e-cypress       
  @vue/cli-plugin-eslint       4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-plugin-eslint
  @vue/cli-plugin-router       4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-plugin-router
  @vue/cli-plugin-typescript   4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-plugin-typescript        
  @vue/cli-plugin-unit-jest    4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-plugin-unit-jest
  @vue/cli-plugin-vuex         4.5.19          4.5.19          5.0.8           vue upgrade @vue/cli-plugin-vuex
? Continue to upgrade these plugins? (Y/n) Yes

...snip...

 DONE  All plugins are up to date!
----

==== Migrate unit tests

For now, the unit test fails with the following errors:

[source,console]
----
> npm run test:unit

> vue3-counter-server-jest-cypress@0.1.0 test:unit
> vue-cli-service test:unit

● Validation Error:

  An unknown error occurred in @vue/cli-plugin-unit-jest/presets/typescript:

  Cannot resolve "@vue/vue3-jest" module. Please make sure you have installed "@vue/vue3-jest" as a dev dependency.
  Error: Cannot resolve "@vue/vue3-jest" module. Please make sure you have installed "@vue/vue3-jest" as a dev dependency.   
ts\default\jest-preset.js:15:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (...\vue3-counter-server\node_modules\@vue\cli-plugin-unit-jest\presets\typescript\jest-preset.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

  Configuration Documentation:
  https://jestjs.io/docs/configuration
----

* Remove `vue-jest@5.0.0-alpha.10`
+
[source,shell]
----
npm uninstall vue-jest
----

* Add `@vue/vue3-jest`
+
[source,shell]
----
npm install --save-dev @vue/vue3-jest@27 babel-jest@27 @types/jest@27
----

* Rerun the unit test to make sure it succeeds:
+
[source,console]
----
vue3-counter-server> npm run test:unit

> vue3-counter-server-jest-cypress@0.1.0 test:unit
> vue-cli-service test:unit

jest-haste-map: Haste module naming collision: vue3-counter-server-jest-cypress
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\package.json
    * <rootDir>\tmp\package.json

 PASS  tests/unit/comp-Counter.spec.js (8.375 s)
 PASS  tests/unit/action.spec.js (14.835 s)   
 PASS  tests/unit/mutation.spec.js (6.903 s)  
 PASS  tests/unit/comp-CounterWithVuex.spec.js (15.546 s)
----------------------|---------|----------|---------|---------|-------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------|---------|----------|---------|---------|-------------------
All files             |     100 |      100 |     100 |     100 |                   
 components           |     100 |      100 |     100 |     100 |                   
  Counter.vue         |     100 |      100 |     100 |     100 |                   
  CounterWithVuex.vue |     100 |      100 |     100 |     100 |                   
 store                |     100 |      100 |     100 |     100 | 
  actions.ts          |     100 |      100 |     100 |     100 | 
  mutations.ts        |     100 |      100 |     100 |     100 | 
 views                |     100 |      100 |     100 |     100 | 
  CounterWithVuex.vue |     100 |      100 |     100 |     100 | 
----------------------|---------|----------|---------|---------|-------------------

Test Suites: 4 passed, 4 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        28.549 s
Ran all test suites.
----

==== Migrate e2e tests

For now, the e2e test fails with the following errors:

* build
+
[source,console]
----
vue3-counter-server> npm run build   

> vue3-counter-server-jest-cypress@0.1.0 build
> vue-cli-service build


✔  Building legacy bundle for production...
 ERROR  Error: Cannot find module 'vue/compiler-sfc'
        Require stack:
        - ...\vue3-counter-server\node_modules\vue-loader\dist\index.js
        - ...\vue3-counter-server\node_modules\@vue\cli-service\lib\config\base.js
        - ...\vue3-counter-server\node_modules\@vue\cli-service\lib\Service.js
        - ...\vue3-counter-server\node_modules\@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- ...\vue3-counter-server\node_modules\vue-loader\dist\index.js
- ...\vue3-counter-server\node_modules\@vue\cli-service\lib\config\base.js
- ...\vue3-counter-server\node_modules\@vue\cli-service\lib\Service.js
- ...\vue3-counter-server\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (...\vue3-counter-server\node_modules\vue-loader\dist\index.js:8:24) 
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
----

* test:e2e
+
[source,console]
----
> npm run test:e2e 

> vue3-counter-server-jest-cypress@0.1.0 test:e2e
> vue-cli-service test:e2e

 INFO  Starting e2e tests...
 INFO  Starting development server...
 ERROR  Error: Cannot find module 'vue/compiler-sfc'
        Require stack:
        - ...\vue3-counter-server\node_modules\vue-loader\dist\index.js
        - ...\vue3-counter-server\node_modules\@vue\cli-service\lib\config\base.js
        - ...\vue3-counter-server\node_modules\@vue\cli-service\lib\Service.js
        - ...\vue3-counter-server\node_modules\@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- ...\vue3-counter-server\node_modules\vue-loader\dist\index.js
- ...\vue3-counter-server\node_modules\@vue\cli-service\lib\config\base.js
- ...\vue3-counter-server\node_modules\@vue\cli-service\lib\Service.js
- ...\vue3-counter-server\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (...\vue3-counter-server\node_modules\vue-loader\dist\index.js:8:24) 
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
----

. Reinstall vue.
+
[source,shell]
----
npm uninstall --save-dev vue-loader vue @vue/compiler-sfc
npm install vue@next
npm install --save-dev @vue/compiler-sfc
----

. Rerun build +
For now, the e2e test fails with the following errors:
+
[source,console]
----
vue3-counter-server> npm run build                                                      

> vue3-counter-server-jest-cypress@0.1.0 build
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠸  Building for production...

 ERROR  Failed to compile with 1 error                                                                               13:50:06

[eslint]
...\vue3-counter-server\src\components\Counter.vue
  23:11  error  Component name "Counter" should always be multi-word  vue/multi-word-component-names

...\vue3-counter-server\src\views\About.vue
  1:1  error  Component name "About" should always be multi-word  vue/multi-word-component-names    

...\vue3-counter-server\src\views\CounterWithVuex.vue
  13:11  error  Component name "Home" should always be multi-word  vue/multi-word-component-names   

...\vue3-counter-server\src\views\Home.vue
  13:11  error  Component name "Home" should always be multi-word  vue/multi-word-component-names   

✖ 4 problems (4 errors, 0 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
    at Hook.eval [as callAsync] (eval at create (...\vue3-counter-server\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (...\vue3-counter-server\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Cache.shutdown (...\vue3-counter-server\node_modules\webpack\lib\Cache.js:150:23)       
    at ...\vue3-counter-server\node_modules\webpack\lib\Compiler.js:1225:15
    at Hook.eval [as callAsync] (eval at create (...\vue3-counter-server\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (...\vue3-counter-server\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.close (...\vue3-counter-server\node_modules\webpack\lib\Compiler.js:1218:23)
----

. Ignore multi word errors (or fix)
+
[source,diff]
.git diff --unified=4 .eslintrc.js
----
@@ -16,8 +16,9 @@ module.exports = {
   rules: {
     "no-console": process.env.NODE_ENV === "production" ? "warn" : "off",
     "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
     "vue/no-multiple-template-root": 0,
+    "vue/multi-word-component-names": 0,
   },
----

==== Update browser

* Make ie11 unsupported
+
[source,diff]
..browserslistrc
----
 > 1%
 last 2 versions
 not dead
+not ie 11
----

. Update browserslist
+
[source,console]
----
> npx browserslist@latest --update-db
Latest version:     1.0.30001363
Installed version:  1.0.30001363
caniuse-lite is up to date
----

==== Update ESLint (2023-03-25)

* Check outdated
+
[source,console]
----
> npm outdated
Package                           Current  Wanted  Latest  Location                                       Depended by
...
@typescript-eslint/eslint-plugin   5.48.1  5.56.0  5.56.0  node_modules/@typescript-eslint/eslint-plugin  vue3-counter-server        
...
@vue/eslint-config-prettier         7.0.0   7.1.0   7.1.0  node_modules/@vue/eslint-config-prettier       vue3-counter-server        
...
eslint                             8.31.0  8.36.0  8.36.0  node_modules/eslint                            vue3-counter-server        
eslint-config-prettier              8.6.0   8.8.0   8.8.0  node_modules/eslint-config-prettier            vue3-counter-server        
eslint-plugin-import               2.26.0  2.27.5  2.27.5  node_modules/eslint-plugin-import              vue3-counter-server        
eslint-plugin-vue                   9.8.0  9.10.0  9.10.0  node_modules/eslint-plugin-vue                 vue3-counter-server        
...
prettier                            2.8.2   2.8.7   2.8.7  node_modules/prettier                          vue3-counter-server        
...
----

. Update ESLint
+
[source,shell]
----
npm install --save-dev --legacy-peer-deps eslint@8 eslint-plugin-import eslint-plugin-vue@9 @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier@8 @vue/eslint-config-prettier@7 prettier
----

. Fix some vulnerabilities
+
[source,shell]
----
npm audit fix
----

. Update browserslist
+
[source,console]
----
> npx browserslist@latest --update-db
...
Latest version:     1.0.30001469
Installed version:  1.0.30001442
...
----

. Confirm it works
+
[source,shell]
----
npm run lint
----

==== Update Vue.js (2023-01-11)

* Update `vue`
+
[source,shell]
----
npm install --save-dev typescript sass sass-loader @vue/compiler-sfc @vue/babel-preset-app
npm install vue vue-router vuex
----
